### ISSUE TITLE
Error in Cata Classic Version

### ISSUE THREAD

**Issue by Aussiewoolf** [timothyrichards/ScarletUI#2]
Please copy the ACE3 Folder AceSerializer-3.0 into your Libs to fix this issue,

Message: Interface/AddOns/ScarletUI/embeds.xml:10 Couldn't open Interface/AddOns/ScarletUI/Libs/AceSerializer-3.0/AceSerializer-3.0.xml
Time: Sun Mar 17 09:57:09 2024

**Comment by Aussiewoolf** [comment]
you have in the embeds.xml , this line
( Include file="Libs\AceSerializer-3.0\AceSerializer-3.0.xml"/)
but in the release the libs folder is LibSerialize instead.

**Comment by timothyrichards** [comment]
I'll take a look at it tonight after work, I appreciate the bug report!

**Comment by timothyrichards** [comment]
should be fixed with: https://github.com/timothyrichards/ScarletUI/commit/065e424022ac57aa1ac0b5be59132027591f15ef

**Comment by Aussiewoolf** [comment]
All good tested on Cata 4.4.0.53750. No bug errors after the update. Thank you

**Comment by timothyrichards** [comment]
thank you again for reporting the issue!
